name: Release

on:
  push:
    branches: [ main ]
    # 移除路径限制，让所有文件都能触发
    # paths:
    #   - '**.go'
    #   - 'templates/**'
    #   - 'static/**'
    #   - 'Dockerfile'
    #   - 'go.mod'
    #   - 'go.sum'
  workflow_dispatch:
    inputs:
      version_type:
        description: '版本类型 (major/minor/patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      manual_version:
        description: '手动指定版本号 (留空自动生成)'
        required: false
        type: string

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[build]') || github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Generate new version
        id: version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 获取最新标签版本
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.9.0")
          echo "Latest tag: $LATEST_TAG"
          
          # 解析版本号
          VERSION=${LATEST_TAG#v}
          IFS='.' read -ra PARTS <<< "$VERSION"
          
          # 检查是否是手动触发
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # 如果提供了手动版本号，则使用它
            if [ ! -z "${{ github.event.inputs.manual_version }}" ]; then
              NEW_VERSION="${{ github.event.inputs.manual_version }}"
              echo "使用手动指定的版本号: $NEW_VERSION"
            else
              # 否则使用版本类型递增
              VERSION_TYPE="${{ github.event.inputs.version_type }}"
              
              MAJOR=${PARTS[0]:-0}
              MINOR=${PARTS[1]:-0}
              PATCH=${PARTS[2]:-0}
              
              case $VERSION_TYPE in
                "major")
                  MAJOR=$((MAJOR + 1))
                  MINOR=0
                  PATCH=0
                  ;;
                "minor")
                  MINOR=$((MINOR + 1))
                  PATCH=0
                  ;;
                *)
                  PATCH=$((PATCH + 1))
                  ;;
              esac
              
              NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
              echo "根据选择的版本类型 $VERSION_TYPE 生成新版本: $NEW_VERSION"
            fi
          else
            # 正常的自动递增补丁版本
            MAJOR=${PARTS[0]:-0}
            MINOR=${PARTS[1]:-0}
            PATCH=${PARTS[2]:-0}
            PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
            echo "自动递增补丁版本: $NEW_VERSION"
          fi
          
          echo "当前版本: $VERSION, 新版本: $NEW_VERSION"
          
          # 更新CHANGELOG
          DATE=$(date +"%Y-%m-%d")
          CHANGELOG_CONTENT="# GoSSH-Web 版本 v$NEW_VERSION ($DATE)\n\n## 更新内容\n\n"
          
          # 获取最近提交
          COMMITS=$(git log $LATEST_TAG..HEAD --pretty=format:"* %s" | grep -v "Merge" || echo "")
          
          # 分类提交信息
          FEATURES=$(echo "$COMMITS" | grep "\[feat\]" | sed 's/\[feat\] //' || echo "")
          FIXES=$(echo "$COMMITS" | grep "\[fix\]" | sed 's/\[fix\] //' || echo "")
          DOCS=$(echo "$COMMITS" | grep "\[docs\]" | sed 's/\[docs\] //' || echo "")
          CHORES=$(echo "$COMMITS" | grep "\[chore\]" | sed 's/\[chore\] //' || echo "")
          OTHERS=$(echo "$COMMITS" | grep -v "\[feat\]\|\[fix\]\|\[docs\]\|\[chore\]" || echo "")
          
          # 添加新功能
          if [ ! -z "$FEATURES" ]; then
            CHANGELOG_CONTENT="${CHANGELOG_CONTENT}### ✨ 新功能\n\n$FEATURES\n\n"
          fi
          
          # 添加修复
          if [ ! -z "$FIXES" ]; then
            CHANGELOG_CONTENT="${CHANGELOG_CONTENT}### 🐛 修复\n\n$FIXES\n\n"
          fi
          
          # 添加文档更新
          if [ ! -z "$DOCS" ]; then
            CHANGELOG_CONTENT="${CHANGELOG_CONTENT}### 📚 文档\n\n$DOCS\n\n"
          fi
          
          # 添加维护更新
          if [ ! -z "$CHORES" ]; then
            CHANGELOG_CONTENT="${CHANGELOG_CONTENT}### 🔧 维护\n\n$CHORES\n\n"
          fi
          
          # 添加其他更新
          if [ ! -z "$OTHERS" ]; then
            CHANGELOG_CONTENT="${CHANGELOG_CONTENT}### 🔄 其他更新\n\n$OTHERS\n\n"
          fi
          
          # 如果没有提交，添加默认消息
          if [ -z "$COMMITS" ]; then
            CHANGELOG_CONTENT="${CHANGELOG_CONTENT}* 维护性更新和优化\n\n"
          fi
          
          # 读取现有的CHANGELOG
          if [ -f "CHANGELOG.md" ]; then
            EXISTING_CHANGELOG=$(cat CHANGELOG.md)
          else
            EXISTING_CHANGELOG=""
          fi
          
          # 合并新旧CHANGELOG
          echo -e "$CHANGELOG_CONTENT" > CHANGELOG.md
          if [ ! -z "$EXISTING_CHANGELOG" ]; then
            echo -e "\n$EXISTING_CHANGELOG" >> CHANGELOG.md
          fi
          
          # 设置Git凭据
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          
          # 提交更新的CHANGELOG
          git add CHANGELOG.md
          git commit -m "[build] Release v$NEW_VERSION"
          git tag v$NEW_VERSION
          
          # 输出版本号
          echo "NEW_VERSION=v$NEW_VERSION" >> $GITHUB_ENV
          echo "version=v$NEW_VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true

      - name: Build
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o gossh-web-linux-amd64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o gossh-web-windows-amd64.exe
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o gossh-web-darwin-amd64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gossh-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gossh-web:${{ env.NEW_VERSION }}
          labels: |
            org.opencontainers.image.title=GoSSH-Web
            org.opencontainers.image.description=强大而现代的Web终端解决方案
            org.opencontainers.image.version=${{ env.NEW_VERSION }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Read Changelog
        id: changelog
        run: |
          VERSION="${{ env.NEW_VERSION }}"
          CHANGELOG=$(awk -v ver="$VERSION" 'BEGIN{flag=0} $0 ~ "# GoSSH-Web 版本 "ver{flag=1;next} $0 ~ "# GoSSH-Web 版本 v"{flag=0} flag{print}' CHANGELOG.md)
          
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}
          body: |
            ${{ env.changelog }}
            
            Docker image tags:
            - ${{ secrets.DOCKERHUB_USERNAME }}/gossh-web:latest
            - ${{ secrets.DOCKERHUB_USERNAME }}/gossh-web:${{ env.NEW_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gossh-web-linux-amd64
          asset_name: gossh-web-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gossh-web-windows-amd64.exe
          asset_name: gossh-web-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gossh-web-darwin-amd64
          asset_name: gossh-web-darwin-amd64
          asset_content_type: application/octet-stream 